[platformio]
build_dir = C:/Users/andy.baker/.platformio/build/tbeam_ntp_server

[env:ttgo-t-beam]
platform = espressif32
board = ttgo-t-beam
framework = arduino
upload_port = COM28
monitor_port = COM28
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.psram = enabled
build_flags =
  -D BOARD_HAS_PSRAM
  -D CORE_DEBUG_LEVEL=3
  -D XPOWERS_CHIP_AXP192
  -mfix-esp32-psram-cache-issue
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
  mikalhart/TinyGPSPlus@^1.1.0
  lewisxhe/XPowersLib
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
